# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20170628_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='highest_bidder',
            field=models.CharField(default='NONE', max_length=55),
        ),
    ]
