# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20170628_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder_id',
            new_name='name',
        ),
    ]
