# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20170629_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
