# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20170629_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
