# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20170629_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner_url',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
