# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20170629_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner_url',
            field=models.CharField(default='NONE', max_length=55),
        ),
    ]
