# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20170701_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='reimbursed',
            field=models.BooleanField(default=False),
        ),
    ]
