# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_reimbursed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='name',
        ),
    ]
